version: '3'
volumes:
  postgres-data:
    driver: local
  app-gems:
    driver: local
  redis-data:
    driver: local

services:
  postgres:
    image: postgres:10.1
    ports:
      - 5432:5432
    volumes:
      # Mount the DB dumps folder into the container, to be able to create & access database dumps:
      - ./db/dumps:/db/dumps
      # Mount out tmp folder, we might want to have access to something there during development:
      - ./tmp:/tmp
      # Mount our 'restoredb' script:
      - ./bin/restoredb:/bin/restoredb:ro
      # Mount our 'dumpdb' script:
      - ./bin/dumpdb:/bin/dumpdb:ro
      # We'll mount the 'postgres-data' volume into the location Postgres stores it's data:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: develop

  redis:
    image: 'redis:3.2'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/redis/data'

  web:
    build: .
    command: ./script/docker/puma.sh
    volumes:
      - .:/pikabu_clone
      - app-gems:/gems
    environment:
      MAILCATCHER_HOST: mailcatcher
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

  sidekiq:
    depends_on:
      - postgres
      - redis
    build: .
    environment:
      MAILCATCHER_HOST: mailcatcher
      REDIS_URL: redis://redis:6379
    command: ./script/docker/sidekiq.sh
    volumes:
      - .:/pikabu_clone
      - app-gems:/gems
