:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - critical
  - default
  - low
  - mailers

:schedule:
  save_top_50_comments:
    cron: '0 5 0 * * *'   # Runs once per day in 0:05
    class: SaveTop50CommentsWorker
  set_post_status_as_hot:
    cron: '0 0 * * * *'   # Runs once per hour
    class: SetPostAsHotWorker
  unban_users:
    cron: '0 0 * * * *'   # Runs once per hour
    class: UnbanUsersWorker
