:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - critical
  - default
  - low

:schedule:
  save_top_50_comments:
    cron: '0 5 0 * * *'   # Runs once per day in 0:05
    class: SaveTop50CommentsJob
